apiVersion: v1
kind: Namespace
metadata:
  name: churn-model
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: churn-model
  annotations:
    serving.kserve.io/s3-endpoint: s3.eu-central-1.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: eu-central-1
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "xxxxxxxxxxxxxxxxxxxxx"
  AWS_SECRET_ACCESS_KEY: "xxxxxxxxxxxxxxxxxxxxxxxx"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: churn-model
secrets:
- name: s3-secret