name: mlops pipeline
on:
  push:
    branches:
      - main

env:
    AWS_REGION: eu-central-1
    S3_BUCKET: churn-model-reddy-bucket-automate
    MODEL_NAME: churn_model.pkl

jobs:
    train-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                token: ${{secrets.GITHUB_TOKEN}}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: generate dataset
              run: python generate_data.py

            - name: train model
              run: python train.py

            - name: configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
            
            - name: upload model to S3
              run: |
                aws s3 cp models/churn_model.pkl s3://${{ env.S3_BUCKET }}/${{ env.MODEL_NAME }}
                echo "Model uploaded to S3 bucket: ${{ env.S3_BUCKET }} with name: ${{ env.MODEL_NAME }}"

            - name: update inference with s3 model path
              run: |
                echo "Updating inference script with S3 model path"
                model_url="s3://${{ env.S3_BUCKET }}/${{ env.MODEL_NAME }}"
                sed -i "s|storageurl = .*|storageurl = '${model_url}'|" k8s/inference.yaml

            - name: commit updated inference script
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add k8s/inference.yaml
                git commit -m "Update inference script with S3 model path"
                git push origin main
